artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_urls: https://drive.google.com/file/d/1YW96OE4y-Uj1N1t35-NzJkOQXbtzx3hZ/view?usp=sharing
  local_data:  artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
   root_dir: artifacts/base_model
   base_model_path: artifacts/base_model/base_model.h5
   updated_base_model_path: artifacts/base_model/updated_base_model.h5


training:
    root_dir: artifacts/training
    trained_model_path: artifacts/training/trained_model.h5




