artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_urls: https://drive.google.com/file/d/1YW96OE4y-Uj1N1t35-NzJkOQXbtzx3hZ/view?usp=sharing
  local_data:  artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



